---
- name: Deploy on OpenStack
  hosts: localhost

  gather_facts: false
  vars_files:
    - vars/main.yml

  tasks:
    - name: Deploy an instance
      os_server:
        state: present
        name: "{{ cloud_name_prefix }}-{{ item.name }}"
        cloud: "{{ cloud_name }}"
        region_name: "{{ cloud_region_name }}"
        availability_zone: "{{ cloud_availability_zone }}"
        image: "{{ cloud_image }}"
        boot_from_volume: true
        terminate_volume: true
        volume_size: 8
        flavor: "{{ cloud_flavor }}"
        key_name: "{{ cloud_key_name }}"
        network: 6efa66eb-9251-41a7-88c3-902753b4940f
        security_groups: "{{ item.security_groups }}"
        floating_ip_pools: public
        timeout: 300
      register: instances
      with_items: "{{ instance_list }}"

    - debug:
        var: instances
        verbosity: 1

    - name: Validate the host is available
      command: >
        ssh -o BatchMode=yes -o StrictHostKeyChecking=no
        centos@{{ item.server.public_v4 }}
      register: result
      until: result|success
      retries: 300
      delay: 5
      with_items: "{{ instances.results }}"
      changed_when: false

    - name: Add host to inventory
      add_host:
        name: "{{ item.item.name }}"
        groups: "{{ item.item.name }}"
        ansible_host: "{{ item.server.public_v4 }}"
        ansible_user: centos
        ansible_become: true
      with_items: "{{ instances.results }}"

